///////////////////////
// Helper Constants
///////////////////////

export const DRAWER_TOGGLED = 'DRAWER_TOGGLED'

///////////////////////
// Profile Constants
///////////////////////

export const SET_PROFILES = 'SET_PROFILES'

export const NEW_PROFILE_FORM_TOGGLED = 'NEW_PROFILE_FORM_TOGGLED'
export const NEW_PROFILE_FORM_CLEAR = 'NEW_PROFILE_FORM_CLEAR'
export const NEW_PROFILE_ERROR_CLEAR = 'NEW_PROFILE_ERROR_CLEAR'
export const NEW_PROFILE_FORM_UPDATED = 'NEW_PROFILE_FORM_UPDATED'
export const NEW_PROFILE_SAVE_STARTED = 'NEW_PROFILE_SAVE_STARTED'
export const NEW_PROFILE_SAVE_FAILED = 'NEW_PROFILE_SAVE_FAILED'
export const NEW_PROFILE_SAVE_SUCCEEDED = 'NEW_PROFILE_SAVE_SUCCEEDED'

export const SET_CURRENT_PROFILE = 'SET_CURRENT_PROFILE'
export const CURRENT_PROFILE_FORM_UPDATE = 'CURRENT_PROFILE_FORM_UPDATE'
export const CURRENT_PROFILE_FORM_CLEAR = 'CURRENT_PROFILE_FORM_CLEAR'
export const CURRENT_PROFILE_LOGIN_STARTED = 'CURRENT_PROFILE_LOGIN_STARTED'
export const CURRENT_PROFILE_LOGIN_SUCCEEDED = 'CURRENT_PROFILE_LOGIN_SUCCEEDED'
export const CURRENT_PROFILE_LOGIN_FAILED = 'CURRENT_PROFILE_LOGIN_FAILED'
export const CURRENT_PROFILE_ERROR_CLEAR = 'CURRENT_PROFILE_ERROR_CLEAR'
export const CURRENT_PROFILE_LOGGED_OUT = 'CURRENT_PROFILE_LOGGED_OUT'

///////////////////////
// Workout Constants
///////////////////////

export const SET_WORKOUTS = 'SET_WORKOUTS'

export const SET_CURRENT_WORKOUT = 'SET_CURRENT_WORKOUT'
export const CURRENT_WORKOUT_LOADING_FAILED = 'CURRENT_WORKOUT_LOADING_FAILED'

export const EDIT_WORKOUT_LOADED = 'EDIT_WORKOUT_LOADED'
export const EDIT_WORKOUT_SAVE_STARTED = 'EDIT_WORKOUT_SAVE_STARTED'
export const EDIT_WORKOUT_SAVE_SUCCEEDED = 'EDIT_WORKOUT_SAVE_SUCCEEDED'
export const EDIT_WORKOUT_SAVE_FAILED = 'EDIT_WORKOUT_SAVE_FAILED'
export const EDIT_WORKOUT_FORM_UPDATED = 'EDIT_WORKOUT_FORM_UPDATED'
export const EDIT_WORKOUT_FORM_TOGGLE = 'EDIT_WORKOUT_FORM_TOGGLE'

/////////////////////////
// listOptions Constants
/////////////////////////

export const FILTER_BAR_TOGGLED = 'FILTER_BAR_TOGGLED'
export const FILTER_KEYS_UPDATED = 'FILTER_KEYS_UPDATED'

export const SORT_DRAWER_TOGGLED = 'SORT_DRAWER_TOGGLED'
export const SORT_OPTION_TOGGLED = 'SORT_OPTION_TOGGLED'
export const LIST_OPTIONS_CLEARED = 'LIST_OPTIONS_CLEARED'
